version: 2.1
jobs:
  oanda-stream_build-and-unit-test_amd64:
    docker:
      - image: cimg/base:2021.04
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
    resource_class: medium+
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "oanda-stream: Build (amd64)"
          working_directory: services/oanda_stream
          command: make build
      - run:
          name: "oanda-stream: Linting"
          working_directory: services/oanda_stream
          command: make linting
      - run:
          name: "oanda-stream: Unit Test"
          working_directory: services/oanda_stream
          command: make unit-test

  oanda-stream_build-and-unit-test_arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "oanda-stream: Build (arm64)"
          working_directory: services/oanda_stream
          command: make build
      - run:
          name: "oanda-stream: Linting"
          working_directory: services/oanda_stream
          command: make linting
      - run:
          name: "oanda-stream: Unit Test"
          working_directory: services/oanda_stream
          command: make unit-test


workflows:
  test_workflow:
    jobs:
      - oanda-stream_build-and-unit-test_amd64
      - oanda-stream_build-and-unit-test_arm64
