version: 2.1
orbs: 
  gcp-gcr: circleci/gcp-gcr@0.15.0

jobs:
  oanda-stream_build-push_amd64:
    docker:
      - image: cimg/base:2021.04
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
    environment:
      GOOGLE_PROJECT_ID: brushed-charts
      GOOGLE_COMPUTE_REGION: europe-west1
    resource_class: medium+
    steps:
      - checkout
      - setup_remote_docker
      - gcp-gcr/gcr-auth:
          registry-url: "europe-docker.pkg.dev/brushed-charts/services"
      - run: export DOCKER_BUILDKIT=0
      - run:
          name: "oanda-stream: Build (amd64)"
          working_directory: services/oanda_stream
          command: make build
      - run:
          name: "oanda-stream: Linting (amd64)"
          working_directory: services/oanda_stream
          command: make linting
      - run:
          name: "oanda-stream: Unit Test (amd64)"
          working_directory: services/oanda_stream
          command: make unit-test
      - run: 
          name: "oanda-stream: push to registry (amd64)"
          working_directory: services/oanda_stream
          command: make push-amd64


  oanda-stream_build-push_arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    environment:
      GOOGLE_PROJECT_ID: brushed-charts
      GOOGLE_COMPUTE_REGION: europe-west1
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          registry-url: "europe-docker.pkg.dev/brushed-charts/services" 
      - run: export DOCKER_BUILDKIT=0
      - run:
          name: "oanda-stream: Build (arm64)"
          working_directory: services/oanda_stream
          command: make build
      - run:
          name: "oanda-stream: Linting (arm64)"
          working_directory: services/oanda_stream
          command: make linting
      - run:
          name: "oanda-stream: Unit Test (arm64)"
          working_directory: services/oanda_stream
          command: make unit-test
      - run: 
          name: "oanda-stream: push to registry (arm64)"
          working_directory: services/oanda_stream
          command: make push-arm64
  

  push-multi-arch:
    docker:
      - image: cimg/base:2021.04
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
    resource_class: small
    environment:
      GOOGLE_PROJECT_ID: brushed-charts
      GOOGLE_COMPUTE_REGION: europe-west1
    steps:
      - checkout
      - gcp-gcr/gcr-auth:
          registry-url: "europe-docker.pkg.dev/brushed-charts/services" 
      - run: export DOCKER_BUILDKIT=0
      - run:
          name: "oanda-stream: create multi-arch manifest"
          working_directory: services/oanda_stream
          command: make arch-fusion
      - run:
          name: "oanda-stream: push manifest"
          working_directory: services/oanda_stream
          command: make push-manifest
  


workflows:
  test_workflow:
    jobs:
      - oanda-stream_build-push_amd64:
          context: brushed-charts
      - oanda-stream_build-push_arm64:
          context: brushed-charts
      - push-multi-arch:
          requires:
            - oanda-stream_build-push_amd64
            - oanda-stream_build-push_arm64
