version: 2.1
jobs:
  oanda-stream-build-amd64:
    docker:
      - image: cimg/base:2021.04
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "oanda-stream: Build (amd64)"
          working_directory: services/oanda_stream
          command: make build
  

  oanda-stream-unit-test:
    docker:
      - image: cimg/base:2021.04
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "oanda-stream: Linting"
          working_directory: services/oanda_stream
          command: make linting
      - run:
          name: "oanda-stream: Unit Test"
          working_directory: services/oanda_stream
          command: make unit-test


  oanda-stream-build-arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "oanda-stream: Build (arm64)"
          working_directory: services/oanda_stream
          command: make build


workflows:
  test_workflow:
    jobs:
      - oanda-stream-build-amd64
      - oanda_stream-unit-test:
          requires:
            - oanda-stream-build-amd64
      - oanda-stream-build-arm64
