version: 2.1
jobs:
  oanda-stream-build-amd64:
    docker:
      - image: cimg/base
        auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "oanda-stream: Build (amd64)"
          working_directory: services/oanda_stream
          command: make build
          

      
  
workflows:
  test_workflow:
    jobs:
      - oanda-stream-build-amd64
