apiVersion: apps/v1
kind: Deployment
metadata:
  name: oanda-stream
  labels:
    app: oanda-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oanda-stream
  template:
    metadata:
      labels:
        app: oanda-stream
        tier: backend
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: oanda-stream
        image: "{{ .Values.images.registryURL }}oanda-stream:1.0"
        volumeMounts:
        - name: etc-volume
          mountPath: /etc/brushed-charts/
          readOnly: true
        envFrom:
          - configMapRef:
              name: general-services
          - configMapRef:
              name: "{{ .Values.profil }}-services"
          - secretRef:
              name: env-secret
        resources:
            limits:
              cpu: 300m
              memory: 80Mi
      volumes:
      - name: etc-volume
        projected:
          sources:
          - secret:
              name: gcp-backend-institution-service-account
          - configMap:
              name: watchlist
              items:
                - key: oanda
                  path: oanda_watchlist.json
          