apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-bigquery
  labels:
    app: health-bigquery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-bigquery
  template:
    metadata:
      labels:
        app: health-bigquery
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: health-bigquery
        image: '{{REGISTRY_URL}}health_bigquery:1.0'
        volumeMounts:
        - name: gcp-service-account
          mountPath: /etc/brushed-charts/
          readOnly: true
        envFrom:
          - configMapRef:
              name: general-services
          - configMapRef:
              name: "{{PROFIL}}-services"
        resources:
            limits:
              cpu: 100m
              memory: 80Mi
      volumes:
        - name: gcp-service-account
          secret:
            secretName: gcp-backend-institution-service-account
          