apiVersion: apps/v1
kind: Deployment
metadata:
  name: oanda-fetcher
  labels:
    app: oanda-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oanda-fetcher
  template:
    metadata:
      labels:
        app: oanda-fetcher
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: oanda-fetcher
        image: '{{REGISTRY_URL}}/oanda_fetcher:1.2'
        volumeMounts:
        - name: gcp-service-account
          mountPath: /etc/brushed-charts/
          readOnly: true
        envFrom:
          - configMapRef:
              name: general-services
          - configMapRef:
              name: "{{PROFIL}}-services"
          - secretRef:
              name: env-secret
        resources:
            limits:
              cpu: 100m
              memory: 80Mi
      volumes:
        - name: gcp-service-account
          secret:
            secretName: gcp-backend-institution-service-account
          