# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: oanda-bigquery
#   labels:
#     app: oanda-bigquery
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: oanda-bigquery
#   template:
#     metadata:
#       labels:
#         app: oanda-bigquery
#     spec:
#       containers:
#       - name: oanda-bigquery
#         # image: '{{REGISTRY_URL}}/oanda_bigquery:{{PROFIL}}-latest'
#         image: 'eu.gcr.io/brushed-charts/oanda_bigquery:dev-latest'
#         imagePullPolicy: Always
#         volumeMounts:
#         - name: gcp-account-service
#           mountPath: /etc/brushed-charts/
#           readOnly: true
#         resources:
#             limits:
#               cpu: 100m
#               memory: 80Mi
#       volumes:
#         - name: gcp-account-service
#           secret:
#             secretName: gcp-backend-institution
